name = "dasollim-portfolio"
compatibility_date = "2024-03-28"

main = "build/server/index.js"
workers_dev = true
node_compat = true

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"
SESSION_SECRET = "your-secure-secret-here"
